---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.name: query-rewrite
  name: query-rewrite
  namespace: prod
spec:
  progressDeadlineSeconds: 600
  replicas: 30
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.name: query-rewrite
  strategy:
#    type: Recreate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.name: query-rewrite
    spec:
      containers:
      - env:
        - name: MCLOUD_AI_ENV
          value: PROD
        image: b66ypcgaicisp01-f8a759e8.ecis.guangzhou-2.cmecloud.cn/prod/query-rewrite:1.0.0-release
        imagePullPolicy: Always
        name: query-rewrite
        resources:
          limits:
            cpu: '4'
            memory: 30Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '4'
            memory: 25Gi
            nvidia.com/gpu: '1'
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /logs
          name: logs
        - mountPath: /etc/localtime
          name: time-localtime
          readOnly: true
        # 设置共享内存
        - name: dshm
          mountPath: /dev/shm
        # 挂载PVC模型目录
        - mountPath: /app/query-rewrite/weights
          name: volume-ai-pvc
          subPath: aimodels/servers/query-rewrite/models
        - mountPath: /data/yun-ai-01
          name: volume-ai-pvc
        - mountPath: /data/yun-ai-02
          name: volume-ai-02
        - mountPath: /data/yun-ai-03
          name: volume-ai-03
      dnsPolicy: ClusterFirst
      nodeSelector:
        gpu-t4: 'true'
      imagePullSecrets:
        - name: cis-auth
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - hostPath:
          path: /var/lib/docker/logs
          type: DirectoryOrCreate
        name: logs
      - hostPath:
          path: /etc/localtime
          type: ''
        name: time-localtime
      # 共享内存
      - name: dshm
        emptyDir:
          medium: Memory
      # 共享存储
      - name: volume-ai-pvc
        persistentVolumeClaim:
          claimName: b130-ypcg-ai-ds-p05-pvc
      - hostPath:
          path: /data/yun-ai-02
          type: Directory
        name: volume-ai-02
      - hostPath:
          path: /data/yun-ai-03
          type: Directory
        name: volume-ai-03
      dnsConfig:
        options:
          - name: single-request-reopen
          - name: timeout
            value: '1'
          - name: attempts
            value: '3'
          - name: ndots
            value: '2'

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.name: query-rewrite
  name: query-rewrite
  namespace: prod
spec:
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: query-rewrite-port
      port: 12330
      protocol: TCP
      targetPort: 12318
  selector:
    app.name: query-rewrite
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  labels:
    app.name: query-rewrite
  name: query-rewrite-in
  namespace: prod
spec:
  ingressClassName: apisix-internal
  rules:
    # 模块名-in是内网
    - host: ai-internal-gzfh.yun.139.com
      http:
        paths:
          - backend:
              service:
                name: query-rewrite-svc
                port:
                  number: 12330
            path: /yun/ai/text/query/rewrite
            pathType: Prefix